ledger/ledger

CMakeLists.txt

http://bugs.ledger-cli.org/show_bug.cgi?id=985
Fix compilation issue on Cygwin by adding the '-U__STRICT_ANSI__' flag
to GCC. This avoids GCC disabling some stdlib functions like 'setenv'
and 'popen'.

Fix for BUG 985

---

lisp/ledger-report.el

Added some lisp code to make sure the cursor is on the same (relative) line in the report buffer after an  auto refresh occured. The behaviour is controlled by the customization option "ledger-report-auto-refresh-sticky-cursor" which is currently default "nil".
This behaviour is much more natural (to my taste) then the jumping up  and down as is without this modification.

ledger-mode bug 1089 introduce sticky cursor for report auto refresh

---

lisp/ledger-fontify.el

This is a subtle bug that happens only when org-src-fontify-natively is
enabled:
```emacs-lisp
(setq org-src-fontify-natively t)
```
If then you create a Babel block with ledger text, it won't be
fontified.
This happens because the 'ledger-fontify-buffer-part' starts
fontification from the current 'point', which in case of
org-src-font-lock-fontify-block happens to _not_ point to the beginning
of buffer. Instead it points to the original org-mode buffer.
This doesn't happen when one opens regular files, because the
'point' is almost always at the beginning of the file.
To reproduce the bug, you can do the following:
```emacs-lisp
(defun fontify-test()
(let ((lang-mode 'ledger-mode) pos next)
(with-current-buffer
(get-buffer-create
"ledger-fontification-bug")
(unless (eq major-mode …
```

[emacs] Fontification should work independentily on where the point currently is

---

lisp/ledger-xact.el

ledger-xact.el:ledger-copy-transaction-at-point (C-c C-k) led to a confusing change in the ledger file for the case when the target date was smaller than last date in the ledger.

[emacs] fix copy

---

doc/ledger3.texi

Make consistent the syntax of "command-line"

---

doc/ledger3.texi

The install instruction in the manual still used an old configure setup. I copied and adjusted the instructions from README.md. For previous discussions see #323.

Manual install instructions

---

src/report.cc
test/regress/1106.test

std::isspace(*e) returns false for the end of c-string null-byte.
Bugzilla: 1106

[fix] Make trim function trim trailing whitespace

---

doc/ledger.1
doc/ledger3.texi

Minor updates to --pager documentation.
I was surprised that this was not documented, I use this option very frequently.
@afh From my point of view this makes no sense to test this as a baseline options. Is there any trick in your python script to authorize to not test --no-pager as a baseline option?
[ci skip]

Add documentation for --no-pager option.

---

doc/ledger.1
doc/ledger3.texi
test/CheckManpage.py
test/CheckOptions.py
test/CheckTexinfo.py
test/DocTests.py

I've changed the formatting of the value expressions using `@defun`, `@defvar`, etc. in the texinfo and to `.It Fn`, `.It Sy` in the manpage, which to me seem the more appropriate texinfo commands for documenting these.
Additionally I've added a `@smallexample`s to some of the value expressions in the texinfo manual, so they are tested and validated by `test/DocTests.py` now! :smile:
The undocumented value expression functions are also reported by `test/CheckManpage.py` and `test/CheckTexinfo.py`
What do you think?

Make documented value expressions testable

---

doc/ledger3.texi

Remove back-link from option to section "balance assertions".
Add forward-link from section to option.
Add option to @findex
[ci skip]

[doc] Improve documentation about "balance assertions" and --permissive

---

.dir-locals.el
contrib/raw/dotemacs.el
contrib/raw/ledger-matching.el
lisp/ledger-commodities.el
lisp/ledger-complete.el
lisp/ledger-exec.el
lisp/ledger-fontify.el
lisp/ledger-init.el
lisp/ledger-mode.el
lisp/ledger-navigate.el
lisp/ledger-occur.el
lisp/ledger-post.el
lisp/ledger-reconcile.el
lisp/ledger-regex.el
lisp/ledger-report.el
lisp/ledger-schedule.el
lisp/ledger-sort.el
lisp/ledger-state.el
lisp/ledger-xact.el

Changes to emacs lisp code are hard to follow and to diff because of tabs. I cleaned the elisp files, but also I added emacs directory local variable to fix more permanently this issue.
[ci skip]

[emacs] Untabify emacs lisp

---

tools/prepare-commit-msg

prepare-commit-msg was failing on my computer, complaining about unexpected '('. This is fixed with commit #62977ea. Other commits are from advise by http://www.shellcheck.net/
[ci skip]

prepare-commit-msg fix

---

acprep

The blame for this section was a bit of a cluster, but, as someone who's not
using Fedora, this makes the most logical sense. (Fedora is a version of RH,
right?)

Fix indentation and position of Fedora test.

---

src/output.cc
src/output.h

Hi @afh.
I hope this is a last try. :)
Here the compile error output, as you want:
===>>> Port directory: /usr/ports/finance/ledger
===>>> Gathering distinfo list for installed ports
===>>> Launching 'make checksum' for finance/ledger in background
===>>> Gathering dependency list for finance/ledger from ports
===>>> Initial dependency check complete for finance/ledger
===>>> Starting build for finance/ledger <<<===
===>>> All dependencies are up to date
===>  Cleaning for ledger-3.1
===>  License BSD3CLAUSE accepted by the user
===>   ledger-3.1 depends on file: /usr/local/sbin/pkg - found
===> Fetching all distfiles required by ledger-3.1 for building
===>  Extracting for ledger-3.1
=> SHA256 Checksum OK for ledger-3.1.tar.gz.
===>  Patching for ledger-3.1
===>   ledger-3.1 depends on …

Fix clang compile error (FreeBSD 10).

---

doc/ledger-mode.texi
lisp/ledger-reconcile.el

Set as an option to kill (or not) the reconcile buffer after
ledger-reconcile-finish.  The default is set to *not* kill the
buffer. This is justified as the facts that:
1. In old ledger mode (the one from Ledger 2.6), the default is to *not*
kill the buffer. Also for the ones who will migrate from 2.6 to 3 when
package will be available in their linux distribution, this will be the
path of least surprise.
2. The current documentation does state that the buffer is to be killed
with 'q' after 'C-c C-c'.
This has been made configurable, as killing buffer may already be part
of the workflow of some persons.
[ci skip]

[emacs] Fix bug 1060.

---

src/global.cc

read_init() was using ~/.ledgerrc instead of ./.ledgerrc if $HOME was set, whether or not ~/.ledgerrc exists. This patch changes it so that ./.ledgerrc will be used if ~/.ledgerrc doesn't exist (or, still, if $HOME is not set for some reason.)

Use ./.ledgerrc if ~/.ledgerrc doesn't exist

---

src/account.h
src/filters.cc
src/item.h
src/iterators.cc
src/parser.h
src/post.h
src/times.h

Can anyone check that this still works for lower boost versions?

build fixes for boost 1.58

---

lisp/ledger-post.el

In emacs 25, save-excursion no longer saves the mark. Running
ledger-post-align-postings now sets the mark, which is annoying.
Moreover, this use of set-mark appears to do nothing, so I removed it.

Do not use set-mark in ledger-post-align-postings

---

lisp/ledger-mode.el

ledger-post-align-postings expects (beg end) not to be optional

Fix ledger-magic-tab: Wrong number of arguments

---

doc/ledger3.texi

Replace `{$5.00}` with `{$50.00}` to be consistent with the example being presented.

Fix Total Commodity Price Example

---

src/CMakeLists.txt

#415 was slightly incorrect; I didn't appreciate that the `ledger` executable embeds a Python interpreter (for `ledger python`, I guess).
Since the ledger executable embeds a Python interpreter, it does need an explicit link to a Python framework on OS X after all.
The dynamic library (which is simply copied into the Python site-packages as the importable module) does not need this link.
This change adds the library linkage back to the `ledger` executable but not the shared library.
It's a little ungainly that the Python stuff is spread out between a couple of different CMakeLists now, I think; I'd be happy to apply some refactoring if there are suggestions.

link ledger executable to Python on OS X

---

lisp/ledger-xact.el

Using `ledger-add-transaction` to add a transaction with a date that places it at the end of the buffer will "forget" to insert the newline between it and the previous transaction. This error occurs in `ledger-xact-find-slot` where the `(when (and (eobp) last-xact-start)` is entered, but subsequently the `(if (eobp))` is false because the point has been moved to the end of the prior exact, which is not the end of the buffer.
The `if` expression is superfluous because the `when` expression has already been entered, and it is broken becase the point gets moved. Removing it fixes the behavior for transactions added at the end
of the buffer, and does not break the behavior for transactions added elsewhere.
This was observed with Emacs 24.5.50.1 and Ledger 3.1.0-20141005.
Please verify this …

Fix xact-find-slot at end of buffer

---

lisp/ledger-mode.el
lisp/ledger-post.el

This patch adds two changes:
1. Add a function to dwim (do what I mean) align: if no region is active, align the xact under the point, if a region is active, align that region.
2. Bind this function to `M-q`.  This might be controversial so I put it in a separate patch, but I think it is a very reasonable idea to replace `fill-paragraph` with something that actually makes sense in ledger mode.

Add dwim align

---

lisp/ledger-post.el

In addition to re-aligning postings, if the point is in a comment, just
fill that comment as regular plaintext.
(cf. #431)

Fill comment paragraph with ledger-post-align-dwim

---

lisp/ledger-post.el
lisp/ledger-regex.el

That is:
A   $10.00
B    $5
C  -$15.00
Before the numbers aligned at the end of the last digit.
@thdox reported this issue to me.  My last align patch broke `,` as decimal separator, that is also fixed.  The bejaviour I "benchmarked" my patch against was master which aligned numbers on the last digit:
A   $10.00
B       $5
C  -$15.00
We both found that undersirable.
If anyone has some edge-cases they feel like we should check, please share :)

Align amounts on the decimal separator.

---

lisp/ledger-commodities.el
lisp/ledger-mode.el

I often spend to the same account from different currencies (I go back and forth from Euro to non-Euro countries), so the quick balance often gets complex and unreadable.
This patch adds two functions:
1. A general facility to ask user for a commodity name
2. Adds `C-u` to `ledger-display-balance-at-point` which causes it to ask for the target commodity and append `-X` switch to the ledger command produced.

Balance at point and target commodity

---

lisp/ledger-post.el

Make the default alignment behaviour the same as before 767ab3e, that
is, align on the last digit by default.  A new option
`ledger-post-amount-alignment-at' now exists to adjust alignment
preference.
This patch addresses @jwiegley's request from #434.

Add an option to change amount-alignment mode.

---

doc/ledger3.texi

I had a problem when going through the tutorial portion of the ledger manual. It was easier for me to cut and paste from the manual to generate the tutorial journal file (drewr3.dat) instead of using the file from the repo itself. However, when I did so, I encountered a run-time error during the 2.2.3 Cleared Report section. After trying to track down what was going on, I realized that the example journal in the manual was actually drewr.dat and not drewr3.dat. So this pull request is to fix the docs so that the example journal is actually drewr3.dat. However, I actually think you should disregard this pull request and fix this problem in a more elegant fashion. Because drewr3.dat has commented out sections and tags that may or may not aid comprehension for the new ledger user (and I just …

Changed drewr.dat to drewr3.dat in docs

---

doc/ledger3.texi

Updating the documentation to remove comments related to GnuCash importing file.

GnuCash import deprecated [ci skip]

---

lisp/ledger-xact.el

Extend the highlighting of the last line in the transaction to the
right margin of the buffer. Do not highlight empty lines.

Fix highlight of the transaction under point

---

lisp/ledger-commodities.el
lisp/ledger-complete.el
lisp/ledger-exec.el
lisp/ledger-occur.el
lisp/ledger-post.el
lisp/ledger-reconcile.el
lisp/ledger-report.el
lisp/ledger-schedule.el
lisp/ledger-sort.el
lisp/ledger-state.el
lisp/ledger-texi.el
lisp/ledger-xact.el

These commits fix all current warnings when byte-compiling on Emacs 24.4.50.2. Mostly they defvar and declare-function various symbols.
[emacs] [ci skip]

Fix warnings

---

src/py_value.cc
test/regress/B21BF389.py
test/regress/B21BF389_py.test

When converting a `ledger.Value` to unicode the Python API added
double quotes around it.
It looks like a bug that was introduced in d5e95720, @jwiegley would you mind having a look please.
To me it does not make sense to have a second `.def("__unicode__", py_dump_relaxed)` in `src/py_value.cc:323` that overwrites the previous `.def("__unicode__", py_value_unicode)` in `src/py_value.cc:317` (see [`src/py_value.cc:317ff`](https://github.com/ledger/ledger/commit/d5e95720#diff-20451a5ff4ce15ef3adc1ad28121d16aR317) or `git show d5e95720:src/py_value.cc | nl -ba | sed -ne '315,325p'`).

[python] Remove double quotes from unicode values

---

README.md

The quick start section is already called "For the Impatient", and this
minor doc tweak should decrease the time and effort demanded of a
new user before their first run by a very tiny amount, and it makes the
README a touch more cohesive.
[ci skip]

[doc] Add "Dependency" anchor link to quick start section

---

contrib/raw/ledger-matching.el

In `ledger-matching.el` require `ledger-report` instead of `ldg-report`.
That library was renamed like all the others.

Require correct feature

---

src/times.cc
test/regress/370-budget_period_days.test
test/regress/370-budget_period_weeks.test
test/regress/370-forecast_period_days.test
test/regress/370-forecast_period_weeks.test
test/regress/370-period.test

My attempt at making day periods have the specified start date.
May resolve bug 370 by replacing biweekly with 14 days in the periodic transaction.

Don't stabilize days periods, reduce number of iterations to find start of period for weeks

---

src/filters.cc
test/regress/1159.test

This allows the offset of a period start to be specified
-p 'every 12 months from 2000-04-01'
will have periods
yyyy-04-01 to yyyy-03-31
....
If no from/since is specified for the period the first transaction date reported is used to initialize the period as before.

Use interval start date (period from/since) to initialize first period.

---

src/textual.cc
test/baseline/feat-balance_assert-off.test
test/baseline/feat-balance_assert_split.test
test/regress/1147-a.test
test/regress/1147-b.test

Fixes [Bug 1147](http://bugs.ledger-cli.org/show_bug.cgi?id=1147)
- Made balance assertions succeed only against the amount _after_ the posting, not before.
- Changed the error message to reflect this (the expected value is the amount _after_).
- Added a regression test.

Fix Bug 1147: Check balance assertions against the amount AFTER

---

src/context.h
src/error.h
src/global.h
src/textual.cc
test/python/JournalTest.py

Parse errors from Python produce RuntimeErrors that str() eval to "".
That is obviously wrong.
This pull request adds the latest context error message to the exception.

Ensure that parse errors produce useful RuntimeErrors for Python code.

---

lisp/ledger-init.el
lisp/ledger-mode.el

I've set `ledger-use-iso-dates` to `t`, but when I add a new entry (with <kbd>C-C C-a</kbd>) followed by a press of <kbd>RET</kbd> to use today's date the format changes to the default format (in my case, because I have no `ledger-environment`). 
This PR extends `ledger-read-date` to use the `ledger-iso-date-format` variable (introduced by this very PR) if `ledger-use-iso-dates` is non-nil.
-Sebastian

Consider ISO dates in `ledger-read-date'.

---

doc/ledger3.texi

I noticed a couple of off-by-one errors in the example describing how to archive previous years.

Fix documentation typos in section 4.9 (Archiving)

---

lisp/ledger-report.el

This makes the current `ledger-binary-path` accessible to ledger reports by using the `%(binary)` format specifier.
It is intended to aid users who may have different `ledger-binary-path` values on different machines. It also means that the default `ledger-reports` will work out of the box even if their ledger executable is not named "ledger" --- for example, if they are using `hledger`, and have otherwise set their binary path appropriately.
This patch would also address [Bug 1172](http://bugs.ledger-cli.org/show_bug.cgi?id=1172).

Adds a "binary" format specifier to ledger-report.

---

lisp/ledger-report.el

This commit adds a new custom `ledger-report-links-in-register` flag that controls whether `ledger-report` will attempt to link transactions in the report buffer to the entries in the original file. Essentially, it controls whether `ledger-report` will silently pass the `--prepend-format` flag to the binary.
The primary motivation for this is that not all implementations of ledger support the `--prepend-format` flag, and thus all "register" commands run by `ledger-report` (and usually *only* "register" commands)
will always fail, because they are treated as a special case in `ledger-do-report`.
At present, the user has no ability to prevent the `--prepend-format` flag from being silently passed to the binary. This PR provides that feature.

Makes links in ledger-report "register" commands optional.

---

doc/ledger3.texi

A minor nitpick in chapter Transaction Notes,
Moving the parenthesis avoids misinterpreting the name "hard separator"
to be a reference to tab-space only.

Documentation - Clarify hard separator explanation

---

acprep

The `ncursesw` port doesn't exist anymore, its functionality is included in the `ncurses` port.

Remove reference to `ncursesw` MacPort.

---

appveyor.yml
src/global.cc
src/main.cc
src/quotes.cc
src/report.cc
src/report.h
src/select.cc
src/stream.cc
src/strptime.cc
src/system.hh.in
src/times.cc
src/utils.cc
src/utils.h
test/unit/t_value.cc

* Appveyor is a continuous integration platform for Windows that is free for open source projects. See latest test build here: https://ci.appveyor.com/project/Evan/ledger/build/artifacts
* Changed WIN32 to _WIN32 because this article [http://nadeausoftware.com/articles/2012/01/c_c_tip_how_use_compiler_predefined_macros_detect_operating_system] claims that it is defined by the greatest number of compilers.
* Modified HAVE_ISATTY and other system defines so that system.hh compiles when cmake fails to find the relevant function.
* Add missing include in test/unit/t_value.cc
Almost all tests fail when you run them on msys32. I will address that in a future PR.

Fix build under msys32; add Appveyor continuous build

---

src/item.h

I recently upgraded from boost 1.60 to 1.61 and ledge compilation fails with a relatively long template error message:
```
In file included from /usr/include/boost/utility/enable_if.hpp:15:0,
from /usr/include/boost/range/has_range_iterator.hpp:21,
from /usr/include/boost/range/difference_type.hpp:21,
from /usr/include/boost/range/size_type.hpp:19,
from /usr/include/boost/range/size.hpp:21,
from /usr/include/boost/range/functions.hpp:20,
from /usr/include/boost/range/iterator_range_core.hpp:38,
from /usr/include/boost/range/iterator_range.hpp:13,
from /usr/include/boost/range/as_literal.hpp:22,
from /usr/include/boost/algorithm/string/trim.hpp:19,
from /usr/include/boost/algorithm/string.hpp:19,
from /home/dkasak/code/ledger/system.hh:174,
from /home/dkasak/code/ledger/src/stats.cc:32: …
```

Fix compilation error with boost 1.61

---

test/regress/383.test

%g is not available in Windows strftime. See documentation at https://msdn.microsoft.com/en-us/library/fe06s4ak.aspx
If this test is meant specifically to test %g as opposed to %y, I will have to come up with another way of fixing this.

Fix regress test 383 on Windows

---

src/textual.cc

This fixes error-in-include.test, dir-apply.test, 6188B0EC.test, and 89233B6D.test when running under msys2 on Windows. The manual computation is incorrect when there are both forward slash and backward slash characters in the path.

Use boost parent_path() method instead of manual computation

---

.gitignore
CMakeLists.txt
CONTRIBUTING.md
README.md
acprep
default.nix
doc/CMakeLists.txt
doc/ledger.1
doc/ledger3.texi
tools/excludes

As ledger-mode has now its own github repository, these changes are updating files which are still referencing old situation.

Ledger mode finalize split

---

test/regress/550-584.test

The file spaces.dat was unused in ledger source code base.
I moved it to test/regress/ so that it is used as regress test for bugs 550 and 584.

Add regress test for bugs 550 and 584

---

.dir-locals.el

Probably a bug in Emacs:
- This add 't' in .dir-locals.el
`M-x add-dir-local-variable RET emacs-lisp-mode RET indent-tabs-mode RET t   RET`
- This does not add 'nil' in .dir-locals.el
`M-x add-dir-local-variable RET emacs-lisp-mode RET indent-tabs-mode RET nil RET`
Fixing this eases the diff between files (spaces instead of tabs). Even if ledger-mode has been moved to its own repository, there are still Emacs lisp files in this repository.

Fix indent-tabs-mode to nil

---

src/output.cc

Remove the following warning from gcc 5.4.0: "[...]/src/output.cc:335:6:
warning: suggest explicit braces to avoid ambiguous ‘else’
[-Wparentheses]".
Instead of adding braces around the whole function body, return early if
item.metadata is 0.

Remove compiler warning about missing braces

---

acprep

The `acprep dependencies` command did not work on Unbtun 16.04 LTS. I just copy-pasted the blocks from Trusty (14.04) and it seems to build and run ok.
Two tests failed:
* BaselineTest_opt-datetime-format
* BaselineTest_opt-time-report
But the output looks ok when I run them, so I'm not sure what the problem is.

Add Ubuntu 16.04 (Xenial) to acprep.

---

src/strptime.cc

This commit: https://github.com/ledger/ledger/commit/c2785590834dfe91574367f4256918c37b6ddfcc fixed the cygwin build but broke MSVC build. This pull request is to fix this.

Fix MSVC build

---

src/textual.cc
test/regress/1182_1.test
test/regress/1182_2.test

Fixes [Bug 1182](http://bugs.ledger-cli.org/show_bug.cgi?id=1182)
- Handled case where parsing a predicate in an automated transaction fails.
- Before it crashed with SIGABRT on `operator->` in Boost's intrusive_ptr.
- Now it throws an error "Expected predicate after '='".
- Added two regression tests.

Fix Bug 1182: Error message for parse failure after '='

---

doc/ledger3.texi

I was updating the tutorial that Conservancy published regarding how it uses Ledger CLI for non-profit accounting and realized that mentioning the tutorial's availability in Ledger's own documentation might be useful as well.
I hereby assert that the copyrights on this contribution are my own and I license them under the license found at the top of file to which this patch applies.

Add mention of third-party tutorials to documentation

---

lisp/ledger-exec.el

When ledger-exec-handle-error is called a second time, it try to insert
the error in a buffer that is already read-only. inhibit-read-only
allow the insertion.

inhibit read only when inserting in *Ledger Error*

---

src/account.cc
test/regress/total-1.test
test/regress/total-2.test

Sorry my C++ is probably terrible...
* Re-initialize (to VOID) totals for the account and its ancestors on adding
postings.  Otherwise the cache intended for use by recursive calls of C++
function total() in computing family (i.e. account hierarchy) totals is
incorrectly retained from one top-level call to the next, causing
inconsistent and broken behaviour.
* Re-initialize (to false) calculated and gathered.  Otherwise we won't
e.g. recalculate stale totals for ancestor accounts (e.g. won't recalculate
Assets:Savings total if Assets:Savings changes via a posting).
Although the value expression total function is used by ledger itself in
computing totals, this bug would only appear on use of .total in user-supplied
value expressions computed *during parsing* of ledger files, rather than …

Fix bug where .total used in value exprs breaks totals

---

src/pool.cc

This trivial PR fixes a bug in ledger when we have costs with lot prices:
2002/03/04 Buy actions
Assets:Broker          10 Foo @ 4 Bar {5.00 EUR}
Assets:Broker
2002/03/04 Buy actions
Assets:Broker          10 Foo @ 4 Bar {6.00 EUR}
Assets:Broker
In the first transaction, ledger sees the first commodity as a `Foo {4 Bar {5.00 EUR}}`, and then when he reads the second, he tries to compare `Bar {5.00 EUR}` with `Bar {6.00 EUR}`, which he cannot.
This modification strips the price of the lot price, thus storing `Foo {4 Bar}` instead of `Foo {4 Bar {5.00 EUR}}`.
Explanations:
Although it makes sense to have cost values dependent on a lot price (for taxation lot tracking), I couldn’t find a valid case where a lot price should itself have a lot price: if 1 Foo has a price 4 Bar, then it’s not …

Strip annotation before adding exchange value

---

src/account.cc

For balance reports ledger uses the `depth_spacer` function.
Alas, when creating reports for LaTeX spaces as indentation don't work.
This commit introduces the `depth_parent` command that returns the indentation level equal to the one used in native balance reports.
The command `depth` returns the depth of the current account, which results in unexpected indentation when some accounts collapse.

Allow printing the depth of the first displayed parent

---

src/py_journal.cc

Allows expanding account aliases in Python.
Example:
```python
>>> import ledger
>>> journal = ledger.read_journal('alias-test.dat')
>>> journal.expand_aliases('Assets:Account:GB04BARC20474473160944').fullname()
'Assets:Current
```
```
account Assets:Current
alias Assets:Account:GB04BARC20474473160944
```

Expose journal expand_aliases to Python

---

src/session.cc
src/session.h

As it does not make sense to use a certain journal file several times we should use a set instead of a list to store the journal file paths in order to ensure that the paths added are actually unique. Unfortunately, this change does not account for the fact that links and relative paths might be used to get different paths that actually point to the same file, but it is a first step in the right direction.
Please don't pull this yet, as its is a work in progress

Use an std::set instead of an std::list to store the the journal file paths

---

README.md

As per https://github.com/Homebrew/homebrew-core/blob/2dfe5715a8f11f07b6460bed40d885c168c09ca7/Formula/ledger.rb#L19 there is `--without-python` instead. The default installs Python bindings.

Homebrew installs Python bindings by default

---

src/report.h

Instead of using a "magic" value (12), use the proper variable to set the width.

Use amount_width variable for budget report

---

src/filters.h
test/regress/market-group-by.test

`changed_value_posts::create_accounts()` reuses the `<Revalued>` account
from `display_filter`, but when clearing `changed_value_posts`
`create_accounts()` would be called before the account had been
recreated by `display_filter_posts`. This results in a segfault when
using the --group-by option.
I'm not sure if `display_filter_posts` has the same problem but I
reordered the calls there too for good measure.

Fix segfault when using --market with --group-by

---

src/xact.cc

Resolve issue where generated balanced postings would become real when the original null post was virtual.
Happens when multiple currencies are mixed with virtual null postings, reproduced like so:
```
2018/01/01 * Virtual
[Account]  -2 USD
[Account]  -2 JPY
[Weird]
```
Would incorrectly generate a real balancing post:
```
$ ledger r
18-Jan-01 Virtual               [Account]                     -2 USD       -2 USD
[Account]                     -2 JPY       -2 JPY
-2 USD
[Weird]                        2 JPY       -2 USD
Weird                          2 USD            0
```

Transfer null_post flags to generated postings

---

src/output.cc
test/baseline/opt-prepend-format.test
test/baseline/opt-prepend-width.test

Add support for the `--prepend-format` and `--prepend-width` options in
the `accounts` command.

Add support for --prepend-format in accounts command

---

src/xact.cc

This fixes some open issues related to balance assertions and auto transactions.
Durring journal parse, the auto xact posts are added but not flagged as visited like normal posts. So when the balance assertion is calculated, the account amount does not include the auto xacts in the calculation.
Should fix #538, #525, and my own use case :)

Fix auto xact posts not getting applied to account total durring journal parse

---

src/filters.cc
test/regress/fix-missing-trans-in-last-budget-period.test

@mthurman as myself found out that posts that belong to a budget are missing from the register report on the last period of a budget.
This should fix that and may replace pull request https://github.com/ledger/ledger/pull/537.
@mthurman thanks for spotting the location this saved me a lot of time.

budget_posts: Keep pending items until the last day they apply

---

src/xact.cc
test/regress/1127.test

This fixes issue #1127.  In my understanding, PR #552 was meant to fix
this, but was incomplete.
Without this patch, automated transactions are invisible to
assertions.
This patch fixes this by adding a flag to the account to tell it that
there is a new posting, analogous to the behavior of finalize().
I dug up issue #1127 too late to find that this is the same solution
proposed by @tbm.  Although I wrote this independently, credit goes to
Martin Michlmayr (@tbm).

Make automated transactions work with assertions

---

src/times.cc
test/regress/1626.test
test/regress/7F3650FD.test
test/regress/BBFA1759.test

This fixes #1626.
The tokenizer eagerly classifies 4-digit integers as TOK_A_YEAR
tokens.  In some contexts such as "every 1000 years", this causes
errors.
I think the tokenizer does not have enough information available to
distinguish between integers and years.
After this patch, the tokenizer will always classify integers as
TOK_INT tokens.  The "has 4 digits" heuristic to determine if an
integer is a year is moved to the place where it's actually
needed (and it can be slightly more generic there, too).

Remove TOK_A_YEAR token

---

src/print.cc

Capture the `std::string` value from options in a local variable that
lives as long as the `c_str()` taken from it to ensure it does not get
freed prematurely.
Fixes: #546

Fix garbled dates when using --date-format

---

src/utils.h

After boostorg/uuid@33da3e2a5b87 (and boostorg/uuid@3d2f7758e9e1) build fails. See [error log](https://ptpb.pw/Mtja).
Can you also backport to `master` and `release/3.1.2` branches?
CC @ilovezfs

Unbreak build against Boost 1.68

---

doc/ledger3.texi
src/textual.cc
test/regress/1187_5.test

I coded a bit on a better fix for issue 1187. What I did:
- the computation of the diff between what is in the account and the assertion is now a `balance_t` instead of `amount_t`, so it handles multiple currencies.
- it then checks only the the commodity specified in the assertion amount when verifying the assertion
- if the assertion value is 0 without a commodity, it will ensure that the diff is zero for all commodities.
Added a test, updated documentation. Feel free to comment.

Improve fix of issue #1187

---

doc/ledger3.texi

Based on my observations. The first behavior makes sense to me. For the second, it would be nice if ledger would enforce `--check-payees` on the tag. In either case I thought it would be helpful to call these out.

Add notes to 5.7.1.1 Payee metadata tag doc

---

contrib/ledger-completion.bash

Add completion of option shorthands `-f`, `-i` and `-o`.
/cc @thdox

Improve bash completion

---

doc/ledger3.texi

Section "Working with multiple funds and accounts" introduces square brackets and explains them but does not explain round brackets in the following example. This commit adds the explanation what the round brackets do.

explain round brackets in section 3.8 on multiple funds

---

src/draft.cc
src/xact.h

Noticed while trying to run with --debug.
Not completely sure about `draft.cc` as I didn't run that, but seems plausible.
Fixes:
Error: boost::bad_format_string: format-string is ill-formed

Fix some boost format strings

---

README.md
acprep

This contains a few fixes for Ubuntu-based systems:
acprep decodes and compares strings (returned from the commands are bytes), which also works with Python3
updated the deps for bionic (18.04) which is the current LTS (Long Term Support) version
adjusted README.md to reflect these newer systems. Also removed instruction for 12.04 (which has not gotten any update since April 28, 2017)

Ubuntu deps update

---

.travis.yml

Commit 4c4367fe6b7f184605c900735fc5b646f45311c1 added some logic to
compile Ledger with GCC 4.8 as Travis CI's Ubuntu Precise environments
only offered 4.6 at that time.  Since then, the default image has
changed to Ubuntu Trusty which provides GCC 4.8.

Use standard GCC in Travis CI

---

src/system.hh.in

FreeBSD 4 was declared end-of-life in 2006
(https://lists.freebsd.org/pipermail/freebsd-security/2006-October/004111.html).
Currently, only FreeBSD 11 and 12 are supported
(https://www.freebsd.org/security/security.html#sup).

Remove workaround for isspace() on FreeBSD 4 and earlier

---

src/py_post.cc

This fixes #1655 by making the post_t::given_cost variable accessible
over python.
This allows access to the given cost of a posting.  For example, here
it will be "-2 EUR":
A  -2 XXX {1 EUR} [2018-01-01] @@ 2 EUR
If a per-unit cost is given, the given_cost variable will still
contain the cost of the posting.  For example, here it will be
"-4 EUR":
B  -2 XXX {1 EUR} [2018-01-01] @ 2 EUR

Expose post_t::given_cost over python

---

doc/NEWS
src/xact.cc
test/regress/1723.test

All-null transactions are discarded and thus freed, but with a deferred
posting this results in a use-after-free error when the deferred
postings are applied.
Ignore null deferred postings to prevent this.
Fixes #1723

Ignore null deferred postings

---

test/CMakeLists.txt
test/unit/CMakeLists.txt

The set_target_properties() commands themselves do not cause the tests
to run if the target check is made, and as the target check executes
ctest, all tests will be run anyway.

Do not set dependencies for target check

---

src/context.h
src/main.cc
src/pyinterp.cc
src/stream.cc
src/textual.cc
src/value.cc
src/value.h

Ledger requires Boost 1.49 or later and enforces this in
CMakeLists.txt.  This means BOOST_VERSION will always be
104900 or higher.  Also, since Boost 1.46,
BOOST_FILESYSTEM_VERSION is 3.

Drop conditionals for Boost earlier than 1.49

---

src/timelog.cc

Checking-in to multiple accounts at a time throws the following error
"When multiple check-ins are active, checking out requires an account"
Issue is that the acount name was sent as 3rd parameter to time_xact_t
constructor whereas it is supposed to be sent as 4th parameter
Corrected the argument position of account name in constructor call to
time_xact_t

Timelog: Not able to check-in to multiple accounts at a time

---

CMakeLists.txt
src/CMakeLists.txt

CMAKE_CXX_COMPILER is the path to the compiler binary and does not
need to follow a specific pattern.  For example, on Linux with GCC and
without an explicit "-DCMAKE_CXX_COMPILER:PATH=" option,
CMAKE_CXX_COMPILER is "/usr/bin/c++" which does not match "g++".
CMAKE_CXX_COMPILER_ID however will always reliably be "Clang" or
"GNU".

Use CMAKE_CXX_COMPILER_ID for conditions based on compiler

---

doc/NEWS
src/filters.h

When using the `--gain` option the `temporaries_t` in
`changed_value_posts` filter stores a reference to the `<Revalued>` temp
account created in `display_filter_posts`. When destroying the filter
chain `display_filter_posts` is destroyed before `changed_value_posts`
and this can result in a use-after-free in `temporaries_t::clear()` when
`temps` in `changed_value_posts` is cleared during destruction if there
are any temp posts referencing the `<Revalued>` account.
Fix the issue by clearing the `temporaries_t` in `changed_value_posts`
before destroying the rest of the filter chain (which includes
`display_filter_posts`).
Fixes #541

Fix use-after-free when destroying filter chain

---

.travis.yml
CMakeLists.txt
src/CMakeLists.txt

On macOS, CMake detects the Boost.Python component installed by
homebrew only when named "python27".  Thus this change not only adds a
Travis CI setup for macOS, but also a CMake option to switch the
component name between "python" and "python27".  In addition,
precompiling system.hh does not work with the current setup for Clang,
so another CMake option to disable it is added.
The currently used commands to compile specific versions of Boost do
not produce a result that works out of the box on macOS.  It should be
possible just to mimic homebrew's formula for boost-python
(https://github.com/Homebrew/homebrew-core/blob/master/Formula/boost-python.rb),
but for the moment on macOS this change tests only against Boost
installed by homebrew.

Add Travis CI setup for macOS and homebrew-installed Boost

---

doc/ledger3.texi

on macos 10.14.2 with
- boost : 1.68.0
- makeinfo : 4.8
- texi2pdf : 1.34
error before correction 
```
/Users/samuel/github.com/ledger/ledger/doc/ledger3.texi:421: Le champ Prev du noeud « Third-Party Ledger Tutorials » n'a pas de pointeur de retour en amont.
/Users/samuel/github.com/ledger/ledger/doc/ledger3.texi:404: Ce noeud (Getting help) a un noeud « Next » erroné.
```

Fix possible fail acprep make doc [ci skip]

---

doc/GLOSSARY.md

"Expenses" was listed twice, one was probably supposed to be "Income".

fix "Income increases with credits"

---

INSTALL.md

I followed the steps in the INSTALL.md and ran into issues.
I would have avoided troubleshooting if the `./acprep dependencies` had been at the top of INSTALL.md
The documentation shows all three steps.

add step $ ./acprep dependencies to INSTALL.md

---

doc/NEWS
src/item.cc
test/regress/1702.test

If a tag is more than 2 characters from the beginning of the comment the
tag value offset will be wrong. #1702 gives an example where the tag
line starts with `;;` and the tag value thus becomes `: Bar` because of
this bug.
The use `index` in the offset calulation seems to be a lucky coincidence
that works in the common case: "; tag: value"
Fixes #1702

Fix tag value parsing

---

src/times.cc
test/regress/1775.test

'%F' is equivalent to '%Y-%m-%d'. Using the '%F' format without this
change this would not give any hard errors but instead give dates with
wrong years because the 'has_year' trait would not be correctly
detected and thus parsed dates would get set to the current year.
Fixes #1775

Add support for '%F' date format specifier

---

doc/ledger3.texi

Currently the docs recommend the use of balance --average to help
generate a budget.  Apparently that doesn't work.  Instead use the
register command with --average.
This fixes #1646

Remove use of balance --average since it doesn't work

---

src/textual.cc

Switch from using utf8::is_bom to utf8::starts_with_bom

---

src/journal.cc
test/baseline/opt-pedantic.test
test/baseline/opt-strict.test

While it seems intentional, elements (accounts, commodities, payees and tags) becoming "known" because they happen to be in a non-uncleared posting is very surprising (and undocumented?) behaviour. It seems to be not very useful and rather unfitting with the terms "strict" and "pedantic".
This PR removes this "know-ification" and updates the tests for strict and pedantic to match their newly expected output.

Remove know-ification of elements due to post state

---

README.md

This will add the instructions to install the latest full release (including the build fix patches for Boost 1.70) with conda to the README.

Add conda installation instructions to README

---

doc/ledger3.texi

This change adds a warning in the documentation for users using automated transactions with `--strict` or `--pedantic`, as ledger will throw an error when `$account` is not defined explicitly (see #545).

Add note regarding $account under --strict or --pedantic modes

---

src/annotate.cc
src/times.cc
test/baseline/opt-register-format.test
test/baseline/opt-rich-data.test
test/regress/78AB4B87_py.test
test/regress/9188F587_py.test

I expect an output of `ledger print` to be consumable by ledger.
But on the next journal
```
2019/11/25 * test
Foo    1 AAPL {1.00 EUR} [2019/11/24]
Bar
```
it prints [19-Nov-24], which it does not understand with default options.
With this patch it prints [2019/11/24].

Format annotations using format that can be parsed

---

src/balance.cc
src/balance.h
src/report.cc
src/report.h

This joins together lots of the same underlying, averaging the reported price
and using the date of the oldest lot.

Add --averaged-lot-prices

---

test/CMakeLists.txt
test/regress/1057.test
test/unit/CMakeLists.txt

python3 has buffered output by default, hence testcase option_py
returned no output when executed under test harness. I think this is a
real problem in the way python interpreter is embeded, and i.e. stdout
is not flushed until after test case has died. However, running things
unbuffered seems to make everything work.
But for some reason I had to adjust 1057.test slightly. I have no idea
what those numbers mean, and if running things unbuffered break stuff.
Should be down to just 6 failures with python3.

test: Unbreak one more test case with python3 bridge

---

default.nix

There is no longer a submodule which provides elisp, so the `cp` portion of this expression fails.
Also remove obsolete comment about presence of gitmodules.
Background to this is that we're using nix to obtain `ledger` for the `ledger-mode` Travis builds, and building from this expression [fails in CI](https://travis-ci.org/ledger/ledger-mode/jobs/594317052).

Remove reference to lisp from default.nix

---

src/journal.cc

This solution does not break any tests, but seems wrong to me: what are the actual invariants w.r.t posts and their associated accounts? What is an xact_t anyway? 
However this is good enough as a workaround for me. Maybe someone else finds it useful as well.

fix #1850: segfault when using ledger print

---

acprep

I wasn't able to install dependencies on my pop-os laptop easily, until I made these changes. I am not sure if these changes involve any pipelines or not, so I didn't do `ci.skip`.

Allow install dev-dependencies on ubuntu-eoan

---

src/filters.cc
src/filters.h
src/journal.h

This fixes #1833 for me. @jwiegley said it's reasonable change, and
nobody else took action so here it goes.
The patch is the same as proposed originally, modulo whitespace.

Specify namespace of uintmax_t

---

test/CMakeLists.txt
test/regress/1057.test
test/unit/CMakeLists.txt

This was regressed in 139beba which set `PYTHONUNBUFFERED` to fix other
test issues. When setting multiple environment variables in this way
they need to be delimited with semicolons rather than spaces. As it is
`PYTHONUNBUFFERED` is being set to `1 TZ=America/Chicago`. The CMake docs
are not as clear about this as they probably should be.
This can be verified by throwing together a CTestTestfile.cmake:
add_test(incorrect_env "printenv" "PYTHONUNBUFFERED" "TZ")
set_tests_properties(incorrect_env PROPERTIES  ENVIRONMENT "PYTHONUNBUFFERED=1 TZ=America/Chicago")
add_test(correct_env "printenv" "PYTHONUNBUFFERED" "TZ")
set_tests_properties(correct_env PROPERTIES  ENVIRONMENT "PYTHONUNBUFFERED=1;TZ=America/Chicago")
When run with `ctest -V`:
1: Test command: /usr/bin/printenv …

Fix setting TZ in tests

---

src/pyinterp.cc
test/CMakeLists.txt
test/unit/CMakeLists.txt

Unbuffer python's stdio to avoid output getting stuck in buffer when
stdout is not a TTY. Normally buffers are flushed by `Py_Finalize` but
Boost has a long-standing issue preventing the proper shutdown of the
interpreter with `Py_Finalize` when embedded [1].
This applies the same fix as 139beba but to any ledger usage rather than
only the test suite. I removed `PYTHONUNBUFFERED=1` from tests as there
is no expectation that users should need to have this set for ledger to
function.
For example without this fix piping ledger into cat usually loses any
output (unless the output is large enough to cause the buffer to flush):
$ ./ledger -f "test/baseline/feat-value_py3.test" reg
<class 'bool'> True
[...]
$ ./ledger -f "test/baseline/feat-value_py3.test" reg | cat
$
Interestingly `--verify` …

py3: ensure python output is not lost

---

.travis.yml
src/CMakeLists.txt

Ledger supports precompiling headers as a build speed optimization.
This is provided via a custom add_pch_rule macro. Similar functionality
is now built-in to CMake starting with the 3.16 release in November
2019. Let's use this when available to fix #1774 and start towards not
needing to maintain our own implementation.
I originally considered removing the macro fallback but in my tests it
saves enough build time that I think it is worth keeping for now.
Fixes #1774

use built-in cmake precompiled header support when available

---

acprep

10.14+ does not support universal builds:
Error: python27 cannot be installed for the configured universal_archs 'x86_64 i386' because the arch(s) 'i386' are not supported.
From https://trac.macports.org/ticket/57369#comment:6
> You just can't install ports universal on Mojave, so don't try to do so. Don't specify +universal on the command line

fix macports dependencies on 10.14+

---

src/account.cc
src/account.h
src/py_account.cc
src/textual.cc
test/regress/543_a.test
test/regress/543_b.test
test/regress/543_c.test
test/regress/543_d.test

Without these changes, whether an account's balance is virtual
or real is not considered when asserting it's balance. This lead
to situations where the user must consider their virtual postings
when attemping to assert the real balance of the account. See
test/regress/543_a.test for that testcase, taken from the original
issue. This commit also includes other, fringe, situations that I
noticed while working on the fix. It essentially just adds a separate
attribute to the account class(?) that hold's the account's "real"
balance, which is only updated when the user attempts an assertion on a
real account. The virtual account's balance is updated the way it always
was.

fix: Fix #543 by tracking an account's real balance

---

.travis.yml

Brew changed boost-python3 to 3.8 but that isn't on the path by default.

fix CI with brew changing to python 3.8

---

test/regress/1894_1.test
test/regress/1894_2.test

Add tests for wrong behavior caused by commit 49b07a1c1948 ("Correction to the way parens are parsed in query expressions") which was reverted with commit 869302ae9ce3.
I made sure the tests fail prior to the fix and pass with the revert applied.

Add regression tests for issue #1894

---

src/CMakeLists.txt

This reverts a change from this commit https://github.com/ledger/ledger/commit/6d4cd58cd4b1b2f3906889009da7b71931645e93#diff-95e351a3805a1dafa85bf20b81d086e6L275 causing issues with the library path.
This should resolve https://github.com/ledger/ledger/issues/1885#issuecomment-625627358

Fix: library path issue

---

default.nix

Without this fix, the Nix build is broken, which causes `ledger-mode` CI builds to fail.
See https://github.com/NixOS/nixpkgs/commit/887295fd2d8c4da06acdaa185cbb3cc214d83285

Remove the-kenny from list of maintainers in default.nix

---

doc/NEWS.md
src/report.h

The code looked for "less" if $PAGER is not set, but it didn't
actually use $PAGER when it it defined.
Fixes #1674

Use PAGER when environment variable is set

---

doc/ledger.1
doc/ledger3.texi
src/chain.cc
src/filters.cc
src/filters.h

This is my attempt to revive PR #216 which was merged prematurely and then reverted again.  I've taken @johannesgerer's original work and built a (hopefully) working implementation of this feature (which was also reqested in #987).
This PR changes the behavior of `--depth` in the register report so that accounts are collapsed to the requested level instead of cut off.  This is essentially the `--collapse` behavior, but the given depth level specifies how far accounts should be collapsed (`--collapse`/`-n` behaves like `--depth 0`).
The following register report
```text
$ ledger reg ^Expenses
20-May-13 Test                Expenses:AA:BB          3.00 EUR    3.00 EUR
Expenses:AA             3.00 EUR    6.00 EUR
20-May-14 Test                Expenses:AA:BB:CC       2.00 EUR    8.00 EUR …
```

Make --depth in register report collapse sub-accounts

---

src/textual.cc

Before this commit, doing something like `include data/*.dat` would
produce undesired behavior because the matches for `data/*.dat` would
not be sorted correctly.
See https://github.com/ledger/ledger/issues/1659 for details.
To verify what is going on, you can use the attached zip file with some test data: 
[ltest.zip](https://github.com/ledger/ledger/files/5009782/ltest.zip)
Do something like
```sh
unzip ~/code/ltest.zip -d /tmp/ && ./ledger -f /tmp/ltest/main.dat bal
```
and on an Ubuntu 18 system you should get a balance assertion error because the files are parsed in the wrong order.
Once you compile with the proposed fix the balance assertion error goes away.

Make it so that the include directive sorts when using wildcards.

---

doc/NEWS.md
doc/ledger.1
doc/ledger3.texi
src/global.cc

`$XDG_CONFIG_HOME/ledger/ledgerrc` and `$HOME/.config/ledger/ledgerrc`
are tried first when looking for an init file.

Add support for `$XDG_CONFIG_HOME`

---

contrib/ledger-completion.bash

Fix shellcheck warning SC2034: command appears unused.
Fix completion script if used by zsh with bashcompinit.

Fix contrib bash-completion

---

src/commodity.cc
test/regress/1998.test

Commit 501fbc08ae5493db77bb34f4c4fbe1f3a3bc14e3 changed the behavior of this function to not return the "equal" result (==0) from the recursive call. Previously, the function returned the result of the recursive call unconditionally.
The new behavior causes an assertion error for certain postings. The regression test added in this commit shows such a posting.
This commit reverts to the old behavior, which fixes issue #1998.

compare_by_commodity: Always return the result of the recursive call

---

doc/ledger3.texi
src/journal.cc
src/journal.h
src/post.cc
src/post.h
src/textual.cc
test/baseline/dir-payee.test
test/baseline/opt-check-payees.test

Hi, everyone! :wave:
Payees declared on posting's metadata are now validated with `--check-payees` option. Also, their aliases are now considered on reports as well.
Fixes https://github.com/ledger/ledger/issues/556.
Fixes https://github.com/ledger/ledger/issues/1892.
Considering the following `test.dat` file:
```ledger
account Assets:Cash
account Expenses:Food
payee Example
tag Payee
commodity $
2020-03-04 Example
Expenses:Food                $20.00 ; Payee: Testing
Assets:Cash
```
```shell
$ ledger -f test.dat reg --pedantic --check-payees
20-Mar-04 Testing                    Expenses:Food                          $20.00          $20.00
Assets:Cash                           $-20.00               0
```
```shell
$ ledger -f test.dat reg --pedantic --check-payees
While parsing file …
```

Fix issues related to payees declared on posting's metadata

---

CONTRIBUTING.md

The "python/server.py" file was removed with fix for #1759.
[ci skip]

Remove obsolete mention of Cheetah web framework.

---

src/draft.cc
test/baseline/cmd-entry.test

Also fix end-of-command boundary checks for keywords "at", "to", etc.

Fix using day-of-week names for `xact` command

---

README.md

Currently the IRC link is broken in the rendered readme page on Github.
Speculating that Github's markdown renderer might not display the text
as a link since it starts with "irc://" instead of "http://" or similar.
> ![ledger-readme-list-bug](https://user-images.githubusercontent.com/43632885/115166764-a7134400-a069-11eb-8e7b-0278f92e4253.png)
Added some text to the bullet point specifying channel and server.
I left the link in-place in case the above issue is resolved at some
point, or if other websites render this README.md file without the
issue.

Fix IRC bullet point in README.md

---

src/amount.cc
test/regress/2001.test

An amount may have a (single) leading minus sign, but none after that.
Bug #2001 (and #1809).

Fix amount tokenizer re: embedded minus sign.

---

src/emacs.cc

Notes were already being escaped. The filename, the transaction code,
the payee, postings' account names, and postings' cost expressions
were not. Everything else the lisp report prints appears to be a
number or a constant-valued non-string token for Lisp.
Here's an example journal file, for reproduction:
```
;; The lisp report prints the quantity as "123 "X Y"",
;; which won't parse properly in Emacs Lisp.
2021/05/30 * Buy some X Y
A  123 "X Y"
Z
;; Here's a pathological transaction with lots of stray double quotes
;; and backslashes. The lisp report won't parse right.
2021/05/30 * (1\2) Bad\ly named"payee 
A:\:B  123 "X Y"
Z
```
This is the output of the lisp report when that content is in /tmp/bad.ledger:
```
(("/tmp/bad.ledger" 4 (24755 3520 0) nil "Buy some X Y"
(5 "A" "123 "X Y"" t) …
```

Escape all string values output by the lisp report.

---

src/expr.cc
src/format.h

We were previously relying on an indirect include within Boost headers. We're
using scoped_ptr which is defined in <boost/smart_ptr/scoped_ptr.hpp>.
Bug: https://bugs.gentoo.org/790176
Closes: #2030

Fix compilation with Boost 1.76

---

acprep

**Problem:**
Unable build `ledger` from source code at Ubuntu 20.04 Focal
```
./acprep dependencies
```
will return
```
acprep: INFO: Invoking primary phase: dependencies
acprep: INFO: Executing phase: dependencies
acprep: INFO: Installing Ledger's build dependencies ...
acprep: INFO: Looks like you are using APT on Ubuntu focal
acprep: INFO: I do not recognize your version of Ubuntu!
```
**Environment:**
```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
```
**Solution:** 
Add 'focal' to ubuntu-releases

acprep: support build on ubuntu 20.04 focal

---

src/textual.cc
test/input/parsing.dat
test/regress/516.test

Handle files that don't end with a new line. Throw an error when the buffer
size is exceeded.
Fixes #516
Contributes to #1149

Fix silent errors when reading lines from input files.

---

.github/workflows/cmake.yml

This update seems to address the problems that others have seen with azure repos disappearing when 
performing an apt-get

Fix for azure ubuntu not getting correct package server

---

src/amount.cc
test/regress/1176.test

While the current formula works for positive numbers, negative numbers
are incorrectly represented.
One of the issues comes from the fact that floor(x) < x for every x.
`amount_t precision` will always be a non negative number and the code
that attempts to fix the issue for negative number will never run.
If we truncate the number instead, the current formula works for both
positive and negative numbers without making negative numbers a corner
case. So let's do that.

Fix --time-colon for negative time amounts

---

src/amount.cc
src/annotate.cc
src/commodity.cc
src/query.cc
src/query.h
src/times.cc
src/token.cc
src/token.h
src/utils.h
test/regress/2058_1.test
test/regress/2058_2.test

This makes it safe to compare results to -1 to indicate EOF,
regardless of whether char is considered signed or unsigned;
and so eliminates compiler warnings on platforms such as ARM.
Fixes bug #2058.

Use correct int return type for stream input operations

---

acprep

I don't know why this is prefilled with `g++`. I was annoyed by it, because my OpenBSD uses clang `c++`. Maybe others, too.

do not enforce GNU C++, allow using c++ (clang)

---

default.nix

`pkgs.stdenv.lib.licenses` is no longer available in recent versions of nixpkgs. Use `lib.licenses` instead.
I think this will fix the build failure in https://github.com/ledger/ledger-mode/pull/323.
Note that this change is already included in #2072, so you don't need this if you merge the PR that adds a flake.

Point licenses to lib.licenses

---

default.nix

@purcell This is a follow-up to the latest PR. #2082 didn't completely fix the error on ledger-mode. I hope this PR will finally fix it.
(I grepped `stdenv.lib`, so there is no other occurrence of the pattern.)

Fix the other occurrences of stdenv.lib

---

contrib/html/README
contrib/html/ledger.xsl

Hi!
ledger-cli xml2html XLST
This XLST produces a browsable html page out of the xml files created by ledger xml.
It might be used in the future to create a ledger html output.
It is not perfect currently, but it is good for my purposes and i might improve it in the future. I thought i would share it for others to be able to find it too.

ledger-cli xml2html XLST

---

src/report.h

Hi, I've tried to make balance report more customisable by replacing hardcoded amount width 20 by `amount_width` option (discussion here https://groups.google.com/g/ledger-cli/c/IX8czQyAL20).
It changes old behaviour because default `amount_width` seems to be equal to 23. This sounds acceptable for me.
However a lot of unit tests failed. E.g.:
```
FAILURE in output from .../ledger/test/manual/transaction-notes-4.test:
--
$ledger -f ".../ledger/test/manual/transaction-notes-4.test" bal food and tag type --account='"Tags:" + tag("Type")'
--
@@ -1,5 +1,5 @@
-               $9.00  Tags
-               $4.50    Coffee:Expenses:Food
-               $4.50    Dining:Expenses:Food
---------------------
-               $9.00
+       $9.00  Tags
+       $4.50    Coffee:Expenses:Food
+       $4.50 …
```

Use amount_width for balance report

---

src/journal.h
src/py_journal.cc

it is currently not required but set. Incidentally, calling file_size()
on a bash pipe e.g. /proc/self/fd/11 fails with:
Error: boost::filesystem::file_size: Operation not permitted: "/proc/self/fd/11"
when executing ledger as
ledger -f <(cat journal)

WIP: fileinfo_t: remove size member

---

src/textual.cc
test/regress/BF3C1F82-2.test

Ensure the path of file to include in `instance_t::include_directive`
is always an absolute path.
Previously when the journal file is given through stdin, we prepend a
"./" to the filename to include. However, in Boost >= 1.77,
`path::normalize` strips the leading "./" [1]. Our `resolve_path`
function calls `normalize` and thus now it returns "file" for "./file"
instead of the previous "./file".
This change causes a failing test regress/BF3C1F82-2 [2], and also
breaks the `include` directive for stdin input:
$ touch file-to-include
$ echo "include file-to-include" | ledger -f - reg
gives
While parsing file "", line 1:
Error: File to include was not found: "file-to-include"
Therefore, we change to prepend the `context.current_directory` to
make the filename absolute in this case as well. …

Ensure absolute path for include

---

NEWS.md

I realized that #2092 introduced some user visible change (the error message). So it might be better to have a NEWS entry for it.

Add a NEWS entry for ba8ec324

---

src/compare.cc
test/regress/2069.test

In `compare_items` if `sort_order` is a top level expression, it has no context and `get_context()` method returns the null pointer. To see this, run
$ ledger -f test/input/demo.ledger --sort display_amount reg --debug scope.symbols
and there will be many lines like
[DEBUG] Binding scope 0 with ...
In such case making a reference to the context is an undefined behavior (honestly the dereferencing itself feels quite problematic, but many compilers just run without any complaints) and could potentially cause segfaults.
Therefore, we change to use only the grandchild scope (`left` or `right`) for `find_sort_values` here. Note that it may seem to be more appropriate to use `report` here for the parent scope. However, in `find_sort_values` which is called right after, the `report` scope is …

Avoid making references to null

---

README.md

Hi!
If I understand it correctly, the README file in this repo is for developers who want to build Ledger. So we have instructions for installing *build dependencies* on Ubuntu, Fedora, and macOS with MacPorts. However, for Homebrew and Conda the instructions are actually on installing the *compiled Ledger cli itself*. That looks a bit confusing and inconsistent. So I update them to give instructions about installing build dependencies.
For conda-forge, I have tested it on a Linux x64 machine. I did not try the Homebrew instructions but the packages are copied from the CI workflow (with `git` and `gpgme` omitted):
https://github.com/ledger/ledger/blob/f3fd025a35b7328f66e21db1eccfe774cae4cf70/.github/workflows/cmake.yml#L47
Thanks!

README.md: Fix for Homebrew and Conda

---

src/textual.cc
test/regress/2109.test

This allows the following to work:
```
2021/11/22 Entry
Assets:Foo        100 FOO (Note) {$43.44}
Income:Bar
2021/11/22 Balance Check
Assets:Foo                                0 = 100 FOO
```
Without this change, you get an error on the balance check because the lot annotations don't match up.

When calculating balance assignments, strip away lot annotations

---

.github/workflows/cmake.yml

`brew install git` [fails on macOS CI job](https://github.com/ledger/ledger/runs/6301580650?check_suite_focus=true)
```
==> Pouring git--2.36.0.big_sur.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink etc/bash_completion.d/git-completion.bash
Target /usr/local/etc/bash_completion.d/git-completion.bash
is a symlink belonging to git@2.35.1. You can unlink it:
brew unlink git@2.35.1
```
I don't think ledger needs the latest git for its tests, so I removed it from `brew install`.
See also:
* https://github.community/t/unable-to-update-homebrews-git-on-macos-runner-without-removing-prebuilt-git-package/246983

Fix CI job on macOS

---

src/chain.cc
src/filters.cc
src/filters.h
test/regress/equity-unround.test

A naive fix that makes `reg --equity --unround` and `equity --unround` work. Today `equity` ignores `--unround` and `reg --equity --unround` doesn't display amounts that are zero when they are rounded. Perhaps we need a more sophisticated fix as it doesn't fix `reg --equity --amount 'unround(amount_expr)'`

Fix unrounding for equity

---

CMakeLists.txt

CMake 3.21.4 reports that compatibility with CMake < 2.8.12 will be removed from a future version of CMake.
CMake 3.0 has new defaults for MACOSX_RPATH. It seems ledger works fine with them. See CMake Policy CMP0042 for the details.
Fixes #1721.

Bump required CMake version

---

acprep

Hello folks,
I just tried to setup the Ledger codebase on Arch Linux and discovered that the `acprep` script does not handle it already.
So I extended it to also work on this distribution.
I followed existing setup for other distros such as Fedora to install all needed dependencies.
So hopefully this is fine.
Thanks.

acprep: add support for arch linux

---

doc/ledger.1
doc/ledger3.texi

The --exchange option can accept multiple comma-separated commodities,
but this is only mentioned in one place where --exchange is documented,
and notably not in the Texinfo manual.
[ci skip]

Document --exchange can accept multiple commodities

---

test/CheckOptions.py
test/DocTests.py
test/LedgerHarness.py
test/RegressTests.py
test/convert.py

to fix failing tests on Darwin, where `/tmp` is a symlink to `/private/tmp` and the tests fail as ledger reports filenames with the symlink resolved to `/private/tmp`, but the tests expect absolute filenames starting with `/tmp`.
Tested using:
<details><summary><code>% nix build</code></summary>
```
% nix build                                                                                      ~src/ledger
error: builder for '/nix/store/479q7ifg9qgxfqwmb4qy9daja1jnkqqz-ledger-3.2.1-dirty.drv' failed with exit code 8;
last 10 log lines:
> 99% tests passed, 4 tests failed out of 400
>
> Total Test time (real) =   5.20 sec
>
> The following tests FAILED:
>         20 - BaselineTest_cmd-convert (Failed)
>        118 - BaselineTest_opt-file (Failed)
>        280 - RegressTest_25A099C9 (Failed) …
```

Replace os.path.abspath with os.path.realpath in tests

---

src/pyinterp.cc

Before, `ledger python -- -c 'raise RuntimeError'` would terminate
messily via SIGABRT, printing the following:
terminate called after throwing an instance of 'int'
[1]    2151711 abort (core dumped)  ledger python -c 'raise RuntimeError'
This change makes the python subcommand throw a standard C++ exception
rather than just a plain int, which is never caught and triggers the
SIGABRT.  Now, the process prints the uncaught Python exception as
usual and then exits with exit code 1.
I tried to make a test case in test/regress but was not able to make it trigger a SIGABRT the same way it did on the command line.  I'm not sure why this is the case, but here is the test case for reference, in case a maintainer wants to fix and add it:
```
test python -- -c 'raise RuntimeError("raising from …
```

Fix SIGABRT when python subcommand raises an exception

---

src/py_utils.cc

replacing it with APIs introduced in Python 3.3 to ensure ledger's Python bindings continue to function when the legacy Unicode API is removed in Python 3.12.
For details see ["Unicode Objects and Codecs" in the Python/C API Reference Manual](https://docs.python.org/3.10/c-api/unicode.html).
<details><summary>Python C/API Deprecation Warnings Emitted During Compilation of Ledger's Python Bindings</summary>
```
~/Developer/ledger/src/py_utils.cc:117:25: warning: '_PyUnicode_get_wstr_length' is deprecated [-Wdeprecated-declarations]
Py_ssize_t size = PyUnicode_GET_SIZE(obj_ptr);
^
/nix/store/6a94sw6yyc412y3a0qjnjdyljx3p1b7n-python3-3.10.5/include/python3.10/cpython/unicodeobject.h:261:7: note: expanded from macro 'PyUnicode_GET_SIZE'
PyUnicode_WSTR_LENGTH(op) :                    \
^ …
```

Fix use of deprecated Python legacy Unicode API

---

python/demo.py
src/py_utils.cc

The changes in this PR address #2132.
The regression was introduced by casting the return value of the different string access macros (e.g. `PyUnicode_1BYTE_DATA`) to `const char*` instead of using the proper typealias (e.g. `Py_UCS1`), which can be an 8, 16, or 32 bit type (see [`python/cpython/Include/unicodeobject.h`](https://github.com/python/cpython/blob/7546914e3f8157d8bad2998677e0ea3ed4cb7939/Include/unicodeobject.h#L100-L104)).
To properly handle the [Euro sign `€`)](https://en.wikipedia.org/wiki/Euro_sign) 16 bits are needed (UCS-2 codepath), yet ledger only allowed for 8, which truncated upper bits of the character for the Euro sign from `U+20AC` to to `U+FFAC`, i.e. `ﾬ`.
While working on this fix to address #2132 I noticed that certain strings (e.g. `¤ 12.34`) are not properly …

Fix regression in Python/C++ unicode string introduced with #2123

---

src/post.cc

In `ledger xml` export, include the `<posting>`-specific payee (from the
`Payee:` tag) as `<payee>`. This data is already included under
`<metadata>` as `<value key="Payee">`, but that is more specific to
Ledger's implementation; if in the future there is another way to set
the payee (or perhaps an option to have the Payee tag in one's own
language), that field wouldn't be a reliable method of getting this
info.
Example:
2022-01-01 Transaction-level payee
a                                             10
b  ; Payee: Posting-level payee
Relevant XML output:
<transaction>
<date>2022-01-01</date>
<payee>Transaction-level payee</payee>
<postings>
<posting>
<account ref="0000558defd6f260">
<name>a</name>
</account>
<post-amount>
<amount>
<quantity>10</quantity>
</amount>
</post-amount>
<total> …

xml: Include posting-specific payee in output

---

src/py_session.cc

Added ledger.session.error_context() to py_session.cc to get the error context message when exceptions are thrown.
This is needed for me as the ArithmeticError thrown when a transaction doesn't balance doesn't include the unbalanced remainder. So adding this allowed me to retrieve the amount that the transaction was off by.
First PR so let me know if anything else is needed. I looked at the python unit tests but looks like they were never updated for python 3.

Add python support for error_context

---

acprep

This PR calls the appropriate `inspect.get(full)argspec` method depending on the Python version being used to run acprep.
This is necessary as `inspect.getargspec` was renamed to `inspect.getfullargspec` in [Python 3.10](https://docs.python.org/3/library/inspect.html#inspect.getfullargspec)

Add compatability for Python 3.10 and later to acprep

---

.github/workflows/cmake.yml

The github mac runner images added python 3.11 but, unlike 3.10, not via brew. This causes `brew install` to fail with link conflict errors now that `boost-python3` switched over to 3.11. Workaround this, and future python brew link errors, by overwriting all links for python packages.
There are a variety of possible solutions here. I went with re-linking all python packages to try to prevent this problem from reoccurring with future python versions; similar issues have been previously reported with the mac github runner images.
I did look into `install --force` as mentioned in #2157. It turns out that still does not overwrite symlinks. From https://docs.brew.sh/Manpage: `-f, --force: [...] When installing casks, overwrite existing files (binaries and symlinks are excluded, unless …

fix brew link error on mac CI

---

src/py_session.cc
test/python/JournalTest.py
test/python/PostingTest.py
test/python/TransactionTest.py

1. Remove references to modules (exceptions, StringIO) no longer needed for Pythn3
2. Use assertEqual instead of assertEquals
3. Clear journal files with a close_journal_files() function that uses the then-current underlying python_session pointer. Calling session.close_journal_files() sometimes leads to segfaults because python_session has changed after it was injected into the python module (as "session") on module startup.

Python: test cleanups

---

src/post.cc
test/baseline/opt-xact-no-payee.test

This is a fix for #2147. Can you please verify that this fix:
1. Does not cause a crash
2. Does not break business logic. i.e transactions are balanced.
This is a naive attempt to fix the issue, I believe a higher level fix is required dealing with scenario where `payee` does not exist. Is it valid to return an empty string? 
In the current logic, it looks like `payee` is expected to be always present, if not, the application crashes due segmentation fault.

Fix for #2147 empty Payee

---

src/amount.h
test/regress/25A099C9.dat
test/regress/89233B6D-a.dat
test/regress/89233B6D-b.dat

https://github.com/ledger/ledger/issues/2159
missed a typo in https://github.com/ledger/ledger/pull/2160/commits/0540ef19dbbdea127f824eba2f8fe8f1bb04b046
src/amount.h
test/regress/25A099C9.dat
```
$ ed -s ledger/test/regress/25A099C9.dat <<<'495p'
to_string() returns an amount'ss "display value" as a string --
$ grep -n amount\'ss ledger/src/amount.h
502:      to_string() returns an amount'ss "display value" as a string --
$ 
```
should have added blank spaces to align columns
test/regress/89233B6D-a.dat
```diff
1994/01/02 * Salary
-     Assets:Bank:Checking               200.00
+     Assets:Bank:Checking                200.00
Income:Salary                      -200.00
```
test/regress/89233B6D-b.dat
```diff
Expenses:Rent                       100.00
-     Assets:Bank:Checking …
```

typo and column alignment

---

doc/ledger.1
doc/ledger3.texi
src/report.cc
src/report.h
test/baseline/opt-csv-format4180.test
test/baseline/opt-csv-formatq.test

Ledger's expression parser considers quoted_rfc4180 to be an amount (quantity 4180 of commodity "quoted_rfc").
Fixes #2007.

Rename quoted_rfc4180 to quoted_rfc, to avoid parser quirk

---

src/pyutils.h
test/python/TransactionTest.py

Setters for types wrapped in `boost::optional`, such as `item_t::note` were broken, e.g. setting a note on a transaction resulted in garbled data that would cause Python to throw utf-8 errors when retrieving the note.
(But setters that accessed strings directly, e.g. "payee" on a transaction worked fine.)
This change alters the from-python conversion for optional-wrapped types based on the example at
https://stackoverflow.com/questions/36485840/wrap-boostoptional-using-boostpython and a test case to verify the behavior.

Fix python/c++ conversion for boost::optional<T>

---

.github/workflows/cmake.yml

as suggested by action warning
For more information see:
https://github.com/ledger/ledger/actions
and
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

Update checkout action to Node.js 16

---

acprep

Adressing latest comment in #2154.
According to the Python documentation [`getargspec`](https://docs.python.org/3.9/library/inspect.html#inspect.getargspec) is
> [d]eprecated since version 3.0: Use [getfullargspec()](https://docs.python.org/3.9/library/inspect.html#inspect.getfullargspec) for an updated API that is usually a drop-in replacement, but also correctly handles function annotations and keyword-only parameters.
Given that support for Python 2 has been dropped in ledger and [getfullargspec()](https://docs.python.org/3.9/library/inspect.html#inspect.getfullargspec) is available in Python 3 this change seems a good solution forward.

acprep: Replace deprecated getargspec with getfullargspec

---

src/post.cc
test/baseline/cmd-stats1.test

When a post has no date at all, default to the current date

---

doc/ledger.1
doc/ledger3.texi

I'm a bit uncertain on how to best integrate links to the documentation for [Boost's default regex dialect](https://www.boost.org/doc/libs/1_81_0/libs/regex/doc/html/boost_regex/syntax/perl_syntax.html) and possibly https://www.pcre.org.
Any ideas or suggestions?
Closes #2145

docs: Specify regex dialect used by ledger

---

src/global.h

What is people's opinion about adding a line to the output of the `--version` option that shows which features have been compiled into Ledger?
**Before**
```console
% ledger --version
Ledger 3.3.0-20230208, the command-line accounting tool
Copyright (c) 2003-2023, John Wiegley.  All rights reserved.
This program is made available under the terms of the BSD Public License.
See LICENSE file included with the distribution for details and disclaimer.
```
**Before**
```console
% ./build/ledger --version
Ledger 3.3.0-20230208, the command-line accounting tool
with support for gpg encrypted journals and with Python support
Copyright (c) 2003-2023, John Wiegley.  All rights reserved.
This program is made available under the terms of the BSD Public License.
See LICENSE file included with the …
```

Add info about compile features to --version

---

doc/ledger.1
src/pyinterp.cc
src/pyinterp.h

Other `server` related code was removed in `013965d0ce1b20e3f8814f65a0d3593c6789bcd7` it seems logical to remove any related left-overs.

Remove unused server related code

---

doc/ledger3.texi

When building the PDF documentation using texinfo, it complains about an incorrect previous node named `Metadata payee` for the `Payee metadata` node. This PR fixes this.

doc: Fix texinfo invalid previous node reference

---

src/textual.cc

Do not perform commodity reduction when parsing a format directive

---

CMakeLists.txt
cmake/LedgerVersion.cmake
doc/CMakeLists.txt

so it can be re-used when generating the version.texi for ledger-website builds.
@tbm I'm working on generating `version.texi` for ledger-website builds, for this the changes in this PR are necessary, so that there is only a single source of truth. A PR for ledger-website ~~will follow shortly~~ is available, see [ledger/ledger-website#53](https://github.com/ledger/ledger-website/pull/53/commits/e6b2f3aa8032d5bdb3bcc554dc5cc57637dbd2eb).

Refactor Ledger version info into cmake/LedgerVersion.cmake

---

CMakeLists.txt

Apologies @tbm, the `PROJECT` cmake statement should not have been removed from CMakeLists.txt, my bad.

Re-add accidentially deleted PROJECT in CMakeLists.txt

---

src/pool.cc

This is needed to avoid a possible divide by zero.

Change a use of is_realzero to just is_zero

---

CMakeLists.txt

I got the version check for Python wrong when updating ledger's dependencies and starting to require Python 3.9.
We want cmake to check that the available Python version is greater than or equal to ledger's minimun required Python version.

Fix Python version check

---

flake.nix
src/account.h
src/amount.cc
src/amount.h
src/annotate.h
src/commodity.h
src/flags.h
src/format.h
src/item.h
src/pstream.h
src/py_account.cc
src/py_amount.cc
src/py_balance.cc
src/py_commodity.cc
src/py_item.cc
src/py_journal.cc
src/py_post.cc
src/py_session.cc
src/py_times.cc
src/py_utils.cc
src/py_value.cc
src/py_xact.cc
src/pyinterp.cc
src/pyinterp.h
src/pyutils.h
src/textual.cc

Looking at the [Ledger class list in the API documentation](https://ledger-cli.org/doc/api/annotated.html) I noticed a few unexpected top-level types related to handling command-line flags and the Python API:
This PR refactors these top-level types into the `ledger`, `ledger::flags`, and `ledger::python` namespaces.
These changes, especially refactoring `basic_flags_t` into `ledger::flags::base_t` may break ledger's API contract. If we believe that it does it might be worthwhile to learn how folks use ledger's API.
I thought it might be helpful to organize ledger's code further into sub-namespaces, i.e. `ledger::flags` and `ledger::python`, but I'm open to having these reside just in `ledger` too.

Clean up class list

---

src/generate.h
src/gpgme.h
src/pyutils.h
src/select.h
src/stats.h
src/unistring.h
src/views.h

Looking at the [Modules in Ledger's API documentation](http://ledger-cli.org/doc/api/modules.html) there appear to be some inconsistencies, e.g. there is a "General utilities" and a "Utils" module, `generate.h` declares `@addotgroup generate` although it later specifies `@ingroup resport`, etc.
This PR tries to clean this up.
@jwiegley do you agree with the proposed changes and could you possibly provide a brief description for the following modules:

Clean-up doxygen modules

---

src/gpgme.cc

Since ledger now required Gpgme >= 1.13.1 (see #2222 for details) code handling prior versions can be removed.
/cc @spacefrogg

gpgme: Remove code handling versions prior to required version

---

NEWS.md
src/item.h
src/xact.cc
test/regress/issue2220.test

This adds a new item flag, `ITEM_INFERRED`, that differentiates generated items from bucket items.
This makes them show up as related items in reports. This is ledger bug #2220.
I've also added a regression test.

Fix bucket transactions with reg --related

---

doc/CMakeLists.txt
doc/ledger.1
doc/mainpage.txt
src/CMakeLists.txt
src/global.h
src/ledger.hh.in
src/pyledger.cc

Unfortunately groff's HTML output of the Ledger man page isn't too readable due to breaks on lines that belong on the same line and with much space between tabbed content. Use of [mandoc(1)](http://mandoc.bsd.lv) remedies that
| Before with `groff` | After with `mandoc`
| --- | ---
| ![Before](https://user-images.githubusercontent.com/16507/233979823-d0de4d88-61c4-40d1-a7ad-e3ef2107f6b3.png) | ![After](https://user-images.githubusercontent.com/16507/233979847-6dd02fad-5daf-473d-94df-8325db6c5a56.png)
A live preview is available at http://projects.surryhill.net/ledger/ledger.html
Future the documentation of the Ledger Python module and package is probably better generated using [sphinx](http://sphinx-doc.org) and the [autodocs](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.h …

Improve web docs

---

src/CMakeLists.txt

when building ledger cli.
Fixes #1913

cmake: Add -fPIC to compile flags

---

CMakeLists.txt
src/CMakeLists.txt

According to the CMake documentation [`add_definitions()`](https://cmake.org/cmake/help/v3.16/command/add_definitions.html?highlight=add_definitions) has been superseded by the alternatives: [`add_compile_definitions()`](https://cmake.org/cmake/help/v3.16/command/add_compile_definitions.html#command:add_compile_definitions), [`include_directories()`](https://cmake.org/cmake/help/v3.16/command/include_directories.html#command:include_directories), and [`add_compile_options()`](https://cmake.org/cmake/help/v3.16/command/add_compile_options.html#command:add_compile_options).

cmake: Replace add_defitions with superseding alternatives

---

src/balance.cc
src/filters.cc
test/regress/2270.test

This fixes #2270 . The cause of the issue was balancing postings were not properly generated when the transaction balance was already zero.

Fix null posting causing error on balanced multi-commodity transaction

---

CONTRIBUTING.md

The `CONTRIBUTING.md` instructions currently imply you should run `acprep` then `cd` into `build` and run `make`/`ninja`, but `acprep` doesn't generate the make file in `build` but in a subdirectory depending on the configuration selected,`build/ledger/debug` by default or `build/ledger/opt` if you pass `opt`.
```
$ git clone https://github.com/ledger/ledger.git
Cloning into 'ledger'...
remote: Enumerating objects: 39563, done.
remote: Counting objects: 100% (636/636), done.
remote: Compressing objects: 100% (279/279), done.
remote: Total 39563 (delta 390), reused 546 (delta 357), pack-reused 38927
Receiving objects: 100% (39563/39563), 18.94 MiB | 19.41 MiB/s, done.
Resolving deltas: 100% (29716/29716), done.
$ cd ledger/
$ mkdir build
$ python3 ./acprep --compiler=clang++
[...]
-- Build …
```

update CONTRIBUTING.md for multiple output directories

---

src/query.cc
test/manual/transaction-notes-1.test
test/regress/1182_2.test
test/unit/t_expr.cc

The manpage documents `=regex` as equivalent to the `note regex` query syntax, but the former does not actually work as the parser only handles an equals sign in the case of `tag type=dining` syntax, and doesn't handle the case where an equals sign starts a note query.
Fixing this does break queries like `tag type = dining` with spaces around the equals sign, but that syntax was not intended or documented.
Closes: #2275

Fix =regex note query syntax

---

flake.lock

The release of NixOS and Nixpkgs 23.11 seems like a good opportunity to update Ledger's flake.lock.

flake: Update to 23.11

---

doc/ledger.1

by using correct special characters as defined in groff_char(7), e.g. using \[aq] instead of "'", as "'" may get displayed as "’" by certain groff output devices, e.g. PDF or utf8.
For details see section _"When viewing man pages, some characters on my UTF-8 terminal emulator look funny or copy-and-paste wrong. Why?"_ in groff's [`PROBLEMS` file](http://git.savannah.gnu.org/cgit/groff.git/tree/PROBLEMS) and the `grotty` section in the [groff 1.23.0 announcement email](https://lists.gnu.org/archive/html/groff/2023-07/msg00051.html).

man: Fix common glyph usage errors

---

acprep

Running `./acprep dependencies` in Ubuntu 22.04 Jammy while building ledger from source returns:
acprep: INFO: Invoking primary phase: dependencies
acprep: INFO: Executing phase: dependencies
acprep: INFO: Installing Ledger's build dependencies ...
acprep: INFO: Looks like you are using APT on Ubuntu jammy
acprep: INFO: I do not recognize your version of Ubuntu!
This error was also present when installing on Ubuntu 20.04 Focal. The solution for Focal is the same for Jammy, which is to add `ubuntu-jammy` to `BoostInfo` and `jammy` as another `release`.

Add support for Ubuntu 22.04 Jammy in ./acprep

---

doc/ledger3.texi

Added to "Transactions and Comments" section 4.7.1 to indicate that posting comments *must* be preceded by at least two spaces.
I also applied this rule consistently to the entire documentation, which only required changes in 4 locations.
I don't think the `ledger` binary cares about spaces in front of posting comments. I never noticed this until I tried using `ledger-mode`'s `ledger-post-edit-amount`, which was causing issues with comments that don't have the proper spacing.

Minor documentation update - on posting comments and fixed some examples

---

test/RegressTests.py

This PR allows to use the test names from ctest output, e.g. `BaselineTest_opt-primary-date` when manually running `RegressTest.py`, e.g. `./test/RegressTests.py -l ./build/ledger -s . RegressTest_A3FA7601`

test: Accept test names as arguments

---

src/history.cc

The given assertion is too strict. If the source and target are the same for a market value valuation, simply return `none`. Note that this happened to me on my data when I was playing around with the `market` function.

Change an assertion into an if test

---

src/error.cc

This limit is just a sanity check, but there is no reason it should be one size or another. I ran into a real world use case where the current limit was much too small.

Expand the size of an arbitrary safety limit

---

src/system.hh.in

Currently, the build with Boost 1.85.0 fails due to usage of removed `convenience.hpp` https://github.com/boostorg/filesystem/commit/5df060e95ca844fe91b29001b4ae22bdb65635c6
I didn't see any usage of removed functionality from header. Main question would be if any indirect headers were used. At least I didn't see any missing headers when compiling with this change.
Ref: https://www.boost.org/doc/libs/1_85_0/libs/filesystem/doc/deprecated.html
---
Seen while updating Boost in https://github.com/Homebrew/homebrew-core/pull/169237

Fix build with Boost 1.85.0

---

src/post.cc
test/regress/2330.test

Part of the `expr_t::compile()` process is to store the current scope, but In `post_t::add_to_value` that scope is temporary and on the stack.
Restore the original context after that process is complete.
Fixes: #2330 #2343

Restore expr context after calc

---

acprep
contrib/non-profit-audit-reports/ooolib2/__init__.py
src/py_utils.cc
src/pyinterp.cc
test/CheckComments.py
test/CheckOptions.py
test/CheckTexinfo.py
test/ConfirmTests.py
test/GenerateTests.py
test/RegressTests.py
test/convert.py
tools/genuuid

for details see individual commits.
The use of raw strings `r''` addresses the following warning `SyntaxWarning: invalid escape sequence \s warning`
Fixes #2332

Improve support for Python version specific code

---

src/print.cc
test/regress/align-amounts.test

When the account name is longer than the --account-width (default 36), the amounts stop aligning:
2023/01/01 Transaction with long account names
Assets:Very:Long:Account:Name:That:Will:Push:The:Amount     -10 ABC
Assets:Another:Long:Account:Name:That:Will:Push:The:Amount     -10 ABC
Expenses:Short                            20 ABC
One can set a larger --account-width, but that is not a great solution for cases where you have only a few accounts with problematically long names. Instead, keep the current account width wherever possible, but when an account name is longer than the account width, account for that and still align the values:
2023/01/01 Transaction with short account names
Assets:Short                             -10 ABC
Assets:Short                             -10 ABC …

print: Align amounts even when account names are long

---

acprep

The script has a syntax error, caused by commit 815305b9: in the `escape_string()` function the first argument to `re.sub()` was probably changed unintentionally, resulting in invalid syntax.
This pull request reverts this one line. To test, I used `./acprep` to build the binary locally, which succeeded. More testing might be needed, I don't have enough context to do that.

Fix acprep script

---

src/amount.cc
src/amount.h
test/unit/t_amount.cc
test/unit/t_balance.cc

- Copy amount quantity before rounding.
- Fix `amount_t::roundto(int)`.
- Transform `balance/testRound` into `balance/testRoundto`. It was a mix of `round` and `roundto` operation with unclear purpose and was relying on `in_place_roundto` behavior modifying all copies.
There is no unit tests for balance `round` and `unround` any more.
Closes #2362

Fix copy on write for amount_t::in_place_roundto

---

src/amount.cc
src/expr.cc
src/format.cc
src/item.cc
src/lookup.cc
src/option.cc
src/pool.cc
src/report.cc
src/strptime.cc
src/textual.cc
src/times.cc
src/utils.cc
src/xact.cc

fix https://github.com/ledger/ledger/issues/2338
fix https://github.com/ledger/ledger/issues/2340

Avoid ctype abuse.

---

src/xact.cc
test/regress/2268.test

This fixes #2268 by preserving the cost from automatic transactions and reflecting it in target transactions.

copy cost from automatic transaction postings

---

src/py_amount.cc
src/py_balance.cc
src/py_value.cc

Expose `roundto` and `in_place_roundto` to `Amount`, `Balance`, and `Value` Python classes.  They may be handy for debugging. The methods were added after introducing of bindings and likely it is a reason why they were missed.
Closes: #2365

Add Python bindings for roundto

---

src/draft.cc
test/regress/2348.test

There were two use-after-free bugs when using `xact`, one was only visible when using `--strict`
This fixes that issue by disabling checking when the `parse_context_stack` is empty, and moving the regex_match parameters into scope.

disable checks for synthetic xacts, fixes  #2348

---

src/amount.cc

Do not serialize to string just to get rounded value. `in_place_roundto` should be reliable enough now.

Avoid string in amount_t::in_place_truncate

---

CMakeLists.txt
src/filters.cc
src/utils.cc
src/utils.h

Updates the build to use C++17, and uses [CMAKE_CXX_STANDARD](https://cmake.org/cmake/help/latest/variable/CMAKE_CXX_STANDARD.html) instead of setting the `-std` flag manually. Using CMAKE_CXX_STANDARD allows the C++ version to decay if/when the compiler doesn't support the requested version, so the version increase shouldn't break builds on older systems.
Fixes #2375

Update to C++17

---

src/filters.cc
src/utils.h

A recent update to Boost changed the type of message digests from `int[5]` to `char[20]`. This PR updates the handling of message digests to use the updated type.
Fixes #2378.

Fix build with Boost 1.86.0

---

src/output.cc
test/regress/cmd-balance-parent-has-transaction.test

Display parent accounts with one child if they contain posts to avoid the user thinking the parent account doesn't have any posts. Previously an account with postings and a child account would just display the child account balance, which hides the actual account balance.
Fixes #2009

Display parent accounts with one child if they contain posts

---

.github/workflows/cmake.yml
CMakeLists.txt
acprep
src/CMakeLists.txt

Main changes:
- Always use precompiled headers, if the configuration option is enabled
- Deprecate `BUILD_DEBUG` and prefer `CMAKE_BUILD_TYPE` to also allow build types like `RelWithDebInfo`

Improve CMake files

---

doc/ledger3.texi

And added footnote explaining "negative number-less notation"
When reading the documentation from top to bottom, the main notation used is the one that has both positive and negative numbers. For example, here: https://github.com/ledger/ledger/blob/master/doc/ledger3.texi#L737-L741. Picture:
The first mention of the "No negative numbers" notation (IINM) is done in chapter 4.1 (Specifically, here: https://github.com/ledger/ledger/blob/master/doc/ledger3.texi#L1544-L1546)
However, in chapter 3.3, the "no negative numbers" notations is used but not explained. Here: https://github.com/ledger/ledger/blob/master/doc/ledger3.texi#L783-L787. And also here: https://github.com/ledger/ledger/blob/master/doc/ledger3.texi#L798-L802. Picture:
Furthermore, in the latter there's a mention to a negative …

Documentation: Added negative numbers for introductory transactions

---

acprep

Update jammy python dependency (acprep dependency install error on Ubuntu 22.04)

---

src/report.cc
test/regress/2403.test

This is a draft PR to get some feedback of whether this is headed into the right direction. If it is, I'll add some tests.
```sh
cat << EOF | nix run github:ledger/ledger/pull/2404/merge -- -f - bal --time-colon --percent
i 2025-01-21 08:00:00 dev:abc  payee
o 2025-01-21 08:45:00
i 2025-01-21 12:00:00 dev:xyz  payee
o 2025-01-21 12:30:00
EOF
100.00%  dev
65.22%    abc
43.48%    xyz
```
Fixes #2403

Fix percentile balance report of time commodity

---

CMakeLists.txt
acprep

In the upcoming Boost 1.89.0 release, Boost.System stub has been removed (https://github.com/boostorg/system/commit/7a495bb46d7ccd808e4be2a6589260839b0fd3a3) which causes CMake error:
```
CMake Error at /opt/homebrew/lib/cmake/Boost-1.89.0/BoostConfig.cmake:141 (find_package):
Could not find a package configuration file provided by "boost_system"
(requested version 1.89.0) with any of the following names:
boost_systemConfig.cmake
boost_system-config.cmake
```
I noticed this while testing 1.89.0.beta1 in Homebrew https://github.com/Homebrew/homebrew-core/pull/233031.
Since master currently requires a minimum of 1.72, it should be safe to remove `system` which was made into a stub back in 1.69[^1]. See `https://github.com/boostorg/system/issues/132#issuecomment-3146378680`
[^1]: …

Fix build with Boost 1.89.0

---

src/gpgme.cc

Just a minor clean-up to avoid use of [deprecated `asString`](https://github.com/gpg/gpgmepp/blob/cd13d4b00cd19d723574acf843abee95111070fb/src/error.h#L50-L53).
We could also update the gpgme dependency requirement to at least gpgme 1.24.0 (released Nov 2024) and always use `asStdString`.
What to people think?

gpgme: Avoid use of deprecated asString

---

test/CMakeLists.txt
test/CheckManpage.py
test/CheckOptions.py
test/CheckTexinfo.py

While debugging #2302 I noticed that `CheckManpage.py` and `CheckTexinfo.py` are not included in the test suite. I believe it is safe to include them even though they currently fail due to missing documentation for a few options and functions (see below), because the tests can only be run if ledger has been built with debug support as the `CheckManpage.py` and `CheckTexinfo.py` (via `CheckOptions.py`) use the ledger option `--debug option.names parse true` which only provides useful information with built with debug support.
@jwiegley from the top of your head could you provide a short description for the following missing option and function documentation (I'm happy to accept this here as a PR comment and take care of the manpage and texinfo syntax)?
```
$ python test/CheckManpage.py -l …
```

test: Include CheckManpage and CheckTexinfo in tests

---

CMakeLists.txt
README.md
acprep

With official [support for Python 3.9 ending around October 2025](https://www.python.org/downloads/) I think it's feasible to bump the minimum required version of Python to 3.10.

Bump required Python version to 3.10

---

src/utils.cc

Address the following warnings during compilation:
```
ledger/src/utils.cc:244:8: warning: function previously declared with an explicit exception specification
redeclared with an implicit exception specification [-Wimplicit-exception-spec-mismatch]
244 | void   operator delete(void * ptr) {
|        ^
/nix/store/3dwjv57wm7w0dl8fqz4x9dczzflwsny4-libcxx-19.1.7-dev/include/c++/v1/new:209:35: note: previous declaration is here
209 | _LIBCPP_OVERRIDABLE_FUNC_VIS void operator delete(void* __p) _NOEXCEPT;
|                                   ^
/Users/afh/Developer/ledger/src/utils.cc:249:8: warning: function previously declared with an explicit exception specification
redeclared with an implicit exception specification [-Wimplicit-exception-spec-mismatch]
249 | void   operator delete[](void * …
```

Address implicit-exception-spec-mismatch warning
