ledger/ledger

acprep
=> Add instructions for Fedora 20.

doc/ledger3.texi
=> Changes mainly about validation of @smallexample

doc/ledger3.texi
=> Improve documentation of --base option

doc/ledger.1, doc/ledger3.texi, src/lookup.cc, test/baseline/opt-auto-match.test
Fix auto match, update test, and improve documentation.
=> Fix Auto match

doc/ledger-mode.texi, lisp/ledger-context.el
My first patch on lisp code. Happy to learn if anything wrong.
=> Fix Bug 1108

src/account.h, src/item.h, src/parser.h, src/post.h, src/times.h
=> Convert boost::optional objects to bool explicitly.

src/value.cc, test/unit/CMakeLists.txt, test/unit/t_value.cc
There was an issue in multiplication in case of sequence. It was due to sequence being added to void value. I added case for void in += operator where any value added to void type value will return the value itself. This sets the void value equal to the added value.
=> Add some unit tests for value_t

doc/ledger3.texi, src/filters.cc, src/filters.h
As discussed on IRC. 
Right now the depth is hard-coded in line 475. This needs to be taken from the command-line argument "--depth" (or 0, if "--collapse" is used).
=> --depth for register

doc/ledger3.texi, src/filters.cc, src/filters.h
=> Revert "--depth for register"

src/emacs.h, test/regress/1057.test
I never understood why PR #305 gathered so many commits not from me. Re-submitting the original one with only 3 commits.
=> Add regression test file for bug #1057

doc/ledger3.texi
=> doc for get_at function

doc/ledger3.texi
In 6.2.1 Controlling the Accounts and Payees:
[...] very power*ful* expression language [...]
=> fix typo in doc

doc/ledger3.texi
as suggested in the mailing list.
=> improve explanation about period expressions

appveyor.yml, test/DocTests.py, test/LedgerHarness.py, test/RegressTests.py, test/regress/981.test
With this change, 97% of the tests pass. See the build on appveyor for more info: https://ci.appveyor.com/project/Evan/ledger/build/build-51
I'll follow up with another PR to fix some of the remaining broken tests
=> Fix test harness to work with msys2

src/global.cc, src/main.cc, src/quotes.cc, src/report.h, src/stream.cc, src/strptime.cc, src/system.hh.in, src/times.cc, test/unit/t_value.cc
Cygwin doesn't define _WIN32, and if you define it, build will fail.
=> Fix build under Cygwin

src/strptime.cc
This fixes the datetime-related tests in testAddition and testSubtraction in the LedgerMathTests
=> Fix Windows strptime

doc/ledger3.texi
- removed redundant preposition
- fixed calculation on unvalidated smallexample block
=> Update ledger3.texi: grammar and typos

src/account.h
Should fix problem with garbage being read from this field causing some
test failures on my machine.
=> Initialize field in constructor

src/py_journal.cc
```python
...
posting = ledger.Posting()
posting.xact = xact
posting.account = journal.register_account('Expenses:Unknown', posting)
```
=> Expose journal_t::register_account to Python

src/report.cc, test/regress/GH520.test
=> Fix handling of edge cases in trim function

doc/ledger3.texi
@jwiegley explained it via IRC just now.
=> Documents commodity directive's alias sub-directive

src/system.hh.in, src/times.cc
The code can be accessed by Git history and reused in a branch if
necessary.
=> Remove unused development code related to USE_BOOST_FACETS

doc/NEWS, src/textual.cc, test/regress/1753.test
=> Reject postings with comment after flag

doc/ledger3.texi
and add some cross references to more detailed documentation and examples.
=> Fix a typo in the documentation

src/account.cc, src/account.h, src/textual.cc, test/regress/543_a.test, test/regress/543_b.test, test/regress/543_c.test, test/regress/543_d.test
Disclaimer: I'm *completely* new to C++ projects, and I only sort of figured out how to write this test tonight by looking at existing merge requests, so if the test is bad please forgive me.
Here I attempt to reproduce error #543 with the hope being that I, or somebody else, can figure out how to fix it.
I don't know how to run the tests on my system, so I don't know where to begin debugging/fixing it, but any help will be appreciated.
=> Fix balance assertions on accounts with virtual posts

README.md, acprep
I don't use macports but I believe this is correct.
Fixes #1847
=> update macports dependencies for python 3 

README.md
Hi,
I've added instructions to README.md to install build dependencies under Fedora 32.
Thanks,
=> Added Fedora build dependencies to README.md

src/format.cc, src/unistring.h, test/unit/CMakeLists.txt, test/unit/t_format.cc
=> format_t::truncate support wide characters

test/RegressTests.py
=> Show "FAILURE in exit code" when success is expected

doc/ledger.1
By the way, is there an ETA for the next release? It would be really nice to have the XDG_CONFIG stuff in the distribution packages.
=> Fix config path in man page

src/textual.cc
=> check that commodity format uses correct symbol

src/report.h
=> Revert "Use amount_width for balance report"

doc/ledger3.texi
=> docs: add instructions for querying quoted commodities

src/commodity.cc
=> Remove some UTF-8 code that was having no effect

src/xact.cc, test/regress/commodity_equivalency.test, test/regress/commodity_equivalency_2.test
=> Fix balancing commodity with smaller unit.

.github/workflows/cmake.yml, test/regress/786A3DD0.test
for debugging.
Attempting to find the cause for #2176…
=> Rerun failed tests with output

doc/ledger3.texi
=> doc: Clarify evaluation of balance assertsions or assignments

doc/ledger3.texi
Not entirely sure what you had in mind @tbm… Hopefully I understood #2151 correctly and this PR addresses the issue.
Closes #2151
=> docs: move section "Payee metadata tag"

doc/ledger3.texi
=> Cross reference Auxiliary and Effective dates sections

flake.nix
See [`ledger/default.nix`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/office/ledger/default.nix) in NixOS/nixpkgs for reference.
=> Update flake.nix to match nixpkgs ledger/default.nix

src/unistring.h
=> Increase string size limit in src/unistring.h assert

flake.nix
=> Require tzdata for Nix flake build

CMakeLists.txt, src/global.h, src/history.cc, src/ledger.hh.in, src/main.cc, src/ptree.cc, src/report.cc, src/report.h, src/select.cc, src/system.hh.in, src/textual.cc, src/utils.cc, src/utils.h
the idea is that any features specific to ledger are defined with a value, e.g. `#define HAVE_GETTEXT 0` and "external" features, like compiler specifics are checked using `#ifdef _GLIBCXX_THROW` or `#if !defined(__clang__)`
=> Cleanup system defines

src/utils.h
See inline comments for details.
=> Fix compilation errors with NO_ASSERT

acprep, contrib/getquote-uk.py, contrib/ledger-du, contrib/non-profit-audit-reports/csv2ods.py, contrib/non-profit-audit-reports/ooolib2/__init__.py, contrib/non-profit-audit-reports/readcsv.py, python/demo.py, test/CheckBaselineTests.py, test/CheckComments.py, test/CheckManpage.py, test/CheckOptions.py, test/CheckTexinfo.py, test/ConfirmTests.py, test/DocTests.py, test/GenerateTests.py, test/LedgerHarness.py, test/RegressTests.py, test/convert.py, test/python/JournalTest.py, test/python/PostingTest.py, test/python/TransactionTest.py, test/regress/B21BF389.py, tools/average, tools/genuuid
as preparatory changes to improve testing ledger.
=> Migrate python scripts

src/query.cc, src/query.h, test/regress/1182_3.test
Contribution from igbanam/ledger#1
Fixes #872
=> Fix Query Parser for Automated Transactions

doc/ledger3.texi
This clarifies how to use value expressions in "rules"
Closes #2358
=> Documentation for auto_xact VEXPR

CONTRIBUTING.md
=> Use https scheme for links in CONTRIBUTING.md

test/regress/2329.test, test/unit/t_amount.cc
- Add some tests from comments to pull request #2361.
- Fix decimal separator in earlier added tests.
=> More unit tests for amount_t::roundto

src/textual.cc, test/regress/1654.test, test/regress/640D3205.test
=> also follow precision from balance assignment

.github/workflows/cmake.yml, acprep
Add support for Ubuntu 24.04 noble in `acprep`
=> acprep: support ubuntu 24.04 noble

.github/workflows/cmake.yml, src/gpgme.cc
which provides GPGME_VERSION_NUMBER
=> Add gpgme.h include
